### ISSUE TITLE
Persist data when the app is closed

### ISSUE THREAD

**Issue by darasat** [junjizhi/flutter-shopping-cart#1]
Good day!

First this Is a great example and easy start for an ecommerce app with flutter.

So I have one question, how we can store the products without losing it when we close and open  the app again ? 

Thank you!

**Comment by nijatmursali** [comment]
Just use shared preferences for that in order to save the data

**Comment by junjizhi** [comment]
@darasat @nijatmursali Using a database like sqlite is likely a better choice than shared preferences. Check out: https://flutter.dev/docs/cookbook/persistence/sqlite
